#!/usr/bin/env bash
# Continuous binlog shipping (F16 / R31.3). Separate from backup.sh.
# Incrementally copies *rotated* binlogs into ARCHIVE_DIR; skips *.index and the
# file still being written; fails loudly on copy/hash mismatch; idempotent.
#
# Env (optional):
#   ENV_FILE                 deploy/.env (default)
#   BINLOG_ARCHIVE_DIR       archive root (default: <repo>/deploy/binlog-archive)
#   BINLOG_RETENTION_DAYS    purge archived files older than N days (0/empty = off)
#   BINLOG_RETENTION_COUNT   keep at most N archived binlog files (0/empty = off)
#   BINLOG_SHIP_DRY_RUN=1    list actions only
#
# Does NOT touch shared DBs by default: only the compose MySQL named in ENV_FILE.
# Prefer a throwaway/dedicated ENV_FILE for drills (see RESTORE-DRILL.md).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/deploy/.env}"
# shellcheck disable=SC1090
set -a && source "$ENV_FILE" && set +a

ARCHIVE_DIR="${BINLOG_ARCHIVE_DIR:-$ROOT/deploy/binlog-archive}"
RETENTION_DAYS="${BINLOG_RETENTION_DAYS:-}"
RETENTION_COUNT="${BINLOG_RETENTION_COUNT:-}"
DRY_RUN="${BINLOG_SHIP_DRY_RUN:-0}"
INVENTORY="$ARCHIVE_DIR/INVENTORY.tsv"
COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$ROOT/deploy/docker-compose.yml")

mkdir -p "$ARCHIVE_DIR"

die() { echo "ship-binlog: ERROR: $*" >&2; exit 1; }
log() { echo "ship-binlog: $*"; }

# Current (open) binlog file — must not be copied (still being written).
current_binlog() {
  # MySQL 8.0.22+: SHOW BINARY LOG STATUS; older: SHOW MASTER STATUS
  local out
  out="$("${COMPOSE[@]}" exec -T mysql \
    mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -N -e \
    "SHOW BINARY LOG STATUS;" 2>/dev/null || true)"
  if [ -z "$(printf '%s' "$out" | tr -d '[:space:]')" ]; then
    out="$("${COMPOSE[@]}" exec -T mysql \
      mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -N -e \
      "SHOW MASTER STATUS;" 2>/dev/null || true)"
  fi
  # First column is File
  printf '%s\n' "$out" | awk 'NF{print $1; exit}'
}

# List binlog paths inside the container (mysql-bin.* or binlog.*).
list_binlog_paths() {
  "${COMPOSE[@]}" exec -T mysql sh -c \
    'ls /var/lib/mysql/mysql-bin.* /var/lib/mysql/binlog.* 2>/dev/null || true'
}

CURRENT="$(current_binlog)"
[ -n "$CURRENT" ] || die "cannot determine current binlog (SHOW BINARY LOG STATUS / MASTER STATUS empty)"
log "current (skip): $CURRENT"
log "archive: $ARCHIVE_DIR"

COPIED=0
SKIPPED=0
FAILED=0

while read -r bin; do
  [ -z "$bin" ] && continue
  base="$(basename "$bin")"
  case "$base" in
    *.index) continue ;;
  esac
  # Only copy rotated files (not the open one).
  if [ "$base" = "$CURRENT" ]; then
    continue
  fi

  dest="$ARCHIVE_DIR/$base"

  if [ -f "$dest" ]; then
    # Idempotent: existing archive must match source size; then verify sha if recorded.
    src_size="$("${COMPOSE[@]}" exec -T mysql sh -c "wc -c < '$bin'" < /dev/null | tr -d '[:space:]')"
    dst_size="$(wc -c < "$dest" | tr -d '[:space:]')"
    if [ "$src_size" != "$dst_size" ]; then
      die "size mismatch for $base (archive=$dst_size source=$src_size); refusing to overwrite (would corrupt chain)"
    fi
    # Optional deep check: re-hash source and compare to inventory / local sha
    if [ -f "$dest.sha256" ]; then
      expect="$(awk '{print $1}' "$dest.sha256")"
      # Re-copy to temp only if we need to re-verify — cheaper: hash local dest
      got="$(sha256sum "$dest" | awk '{print $1}')"
      if [ "$expect" != "$got" ]; then
        die "sha256 mismatch for archived $base (inventory/sidecar vs file); refusing to continue"
      fi
    fi
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  if [ "$DRY_RUN" = "1" ]; then
    log "DRY_RUN would copy $base"
    COPIED=$((COPIED + 1))
    continue
  fi

  tmp="$dest.partial.$$"
  # </dev/null: compose exec must not steal while-read stdin
  if ! "${COMPOSE[@]}" exec -T mysql sh -c "cat '$bin'" < /dev/null > "$tmp"; then
    rm -f "$tmp"
    die "failed to copy $bin"
  fi
  src_size="$("${COMPOSE[@]}" exec -T mysql sh -c "wc -c < '$bin'" < /dev/null | tr -d '[:space:]')"
  dst_size="$(wc -c < "$tmp" | tr -d '[:space:]')"
  if [ -z "$src_size" ] || [ "$src_size" != "$dst_size" ]; then
    rm -f "$tmp"
    die "post-copy size mismatch for $base (source=$src_size copy=$dst_size)"
  fi
  sha="$(sha256sum "$tmp" | awk '{print $1}')"
  printf '%s  %s\n' "$sha" "$base" > "$tmp.sha256"
  mv -f "$tmp" "$dest"
  mv -f "$tmp.sha256" "$dest.sha256"
  log "copied $base size=$dst_size sha256=$sha"
  COPIED=$((COPIED + 1))
done < <(list_binlog_paths)

# Rebuild human-readable inventory (name, size, sha256, mtime UTC).
{
  printf '# binlog archive inventory — regenerated by ship-binlog.sh\n'
  printf '# archive_dir\t%s\n' "$ARCHIVE_DIR"
  printf '# generated_utc\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'name\tsize\tsha256\tmtime_utc\n'
  shopt -s nullglob
  for f in "$ARCHIVE_DIR"/mysql-bin.* "$ARCHIVE_DIR"/binlog.*; do
    [ -f "$f" ] || continue
    case "$f" in *.partial.*|*.sha256|*.index) continue ;; esac
    base="$(basename "$f")"
    size="$(wc -c < "$f" | tr -d '[:space:]')"
    if [ -f "$f.sha256" ]; then
      sha="$(awk '{print $1}' "$f.sha256")"
    else
      sha="$(sha256sum "$f" | awk '{print $1}')"
      printf '%s  %s\n' "$sha" "$base" > "$f.sha256"
    fi
    mtime="$(date -u -r "$f" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "@$(stat -c %Y "$f")" +%Y-%m-%dT%H:%M:%SZ)"
    printf '%s\t%s\t%s\t%s\n' "$base" "$size" "$sha" "$mtime"
  done | sort
} > "$INVENTORY.tmp"
mv -f "$INVENTORY.tmp" "$INVENTORY"
log "inventory: $INVENTORY"

# Retention: by age and/or count (oldest first). Never delete the inventory itself.
purge_one() {
  local f="$1"
  local base
  base="$(basename "$f")"
  if [ "$DRY_RUN" = "1" ]; then
    log "DRY_RUN would purge $base"
    return 0
  fi
  rm -f "$f" "$f.sha256"
  log "purged $base (retention)"
}

if [ -n "$RETENTION_DAYS" ] && [ "$RETENTION_DAYS" -gt 0 ] 2>/dev/null; then
  cutoff="$(date -u -d "-${RETENTION_DAYS} days" +%s 2>/dev/null || date -u -v-${RETENTION_DAYS}d +%s)"
  shopt -s nullglob
  for f in "$ARCHIVE_DIR"/mysql-bin.* "$ARCHIVE_DIR"/binlog.*; do
    [ -f "$f" ] || continue
    case "$f" in *.partial.*|*.sha256|*.index) continue ;; esac
    mt="$(stat -c %Y "$f")"
    if [ "$mt" -lt "$cutoff" ]; then
      purge_one "$f"
    fi
  done
fi

if [ -n "$RETENTION_COUNT" ] && [ "$RETENTION_COUNT" -gt 0 ] 2>/dev/null; then
  mapfile -t ALL < <(ls "$ARCHIVE_DIR"/mysql-bin.* "$ARCHIVE_DIR"/binlog.* 2>/dev/null | grep -vE '\.(sha256|index|partial\.)' | sort || true)
  # Filter to real files only
  FILES=()
  for f in "${ALL[@]:-}"; do
    [ -n "${f:-}" ] && [ -f "$f" ] && FILES+=("$f")
  done
  n="${#FILES[@]}"
  if [ "$n" -gt "$RETENTION_COUNT" ]; then
    excess=$((n - RETENTION_COUNT))
    for ((i = 0; i < excess; i++)); do
      purge_one "${FILES[$i]}"
    done
  fi
fi

# Refresh inventory after purge
if [ "$COPIED" -gt 0 ] || [ -n "${RETENTION_DAYS:-}" ] || [ -n "${RETENTION_COUNT:-}" ]; then
  {
    printf '# binlog archive inventory — regenerated by ship-binlog.sh\n'
    printf '# archive_dir\t%s\n' "$ARCHIVE_DIR"
    printf '# generated_utc\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'name\tsize\tsha256\tmtime_utc\n'
    shopt -s nullglob
    for f in "$ARCHIVE_DIR"/mysql-bin.* "$ARCHIVE_DIR"/binlog.*; do
      [ -f "$f" ] || continue
      case "$f" in *.partial.*|*.sha256|*.index) continue ;; esac
      base="$(basename "$f")"
      size="$(wc -c < "$f" | tr -d '[:space:]')"
      if [ -f "$f.sha256" ]; then
        sha="$(awk '{print $1}' "$f.sha256")"
      else
        sha="$(sha256sum "$f" | awk '{print $1}')"
      fi
      mtime="$(date -u -r "$f" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "@$(stat -c %Y "$f")" +%Y-%m-%dT%H:%M:%SZ)"
      printf '%s\t%s\t%s\t%s\n' "$base" "$size" "$sha" "$mtime"
    done | sort
  } > "$INVENTORY.tmp"
  mv -f "$INVENTORY.tmp" "$INVENTORY"
fi

log "done copied=$COPIED skipped_existing=$SKIPPED archive=$ARCHIVE_DIR"
[ "$FAILED" -eq 0 ] || exit 1
