spring:
  data:
    redis:
      host: ${REDIS_HOST:192.168.88.149}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:8whh6RCl8t6ilKHe8KM4}
      database: ${REDIS_DATABASE:2}
sa-token:
  timeout: 1800
  active-timeout: 1800
  is-concurrent: true
  is-share: false
  max-login-count: 2
  is-log: false
