ALTER TABLE task_step_platform
  ADD COLUMN action_type   VARCHAR(32)  NULL COMMENT 'NONE|CLAIM_REWARD|OPEN_URL|NATIVE_SCHEME|MINIAPP_PATH|SHARE',
  ADD COLUMN action_config VARCHAR(512) NULL COMMENT 'JSON params for action';
