/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/task/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PROGRESS 进度上报
         * @description HMAC 四头；reportId 去重
         */
        post: operations["progress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/task/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CALLBACK 步骤回调
         * @description HMAC 四头；bizNo 覆盖 last_biz_no
         */
        post: operations["callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/reward/fulfillment/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 第三方履约回执
         * @description HMAC 四头；SUCCESS→ARRIVED，FAILED 计次
         */
        post: operations["callback_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InternalProgressCommand: {
            /** Format: int64 */
            instanceId?: number;
            /** Format: int64 */
            userId?: number;
            taskCode?: string;
            cycleKey?: string;
            stepCode: string;
            /** Format: int32 */
            value: number;
            reportId: string;
        };
        ResultTaskProgressResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TaskProgressResponse"];
            traceId?: string;
        };
        TaskProgressResponse: {
            /** Format: int64 */
            instanceId?: number;
            stepCode?: string;
            /** Format: int32 */
            progressCurrent?: number;
            /** Format: int32 */
            progressTarget?: number;
            stepStatus?: string;
        };
        InternalCallbackCommand: {
            /** Format: int64 */
            instanceId?: number;
            /** Format: int64 */
            userId?: number;
            taskCode?: string;
            cycleKey?: string;
            stepCode: string;
            bizNo?: string;
        };
        ResultTaskCallbackResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TaskCallbackResponse"];
            traceId?: string;
        };
        TaskCallbackResponse: {
            /** Format: int64 */
            instanceId?: number;
            stepCode?: string;
            stepStatus?: string;
            instanceStatus?: string;
        };
        FulfillmentCallbackCommand: {
            fulfillmentRef: string;
            result: string;
            failReason?: string;
        };
        FulfillmentCallbackResponse: {
            fulfillmentStatus?: string;
            superseded?: boolean;
        };
        ResultFulfillmentCallbackResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["FulfillmentCallbackResponse"];
            traceId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    progress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalProgressCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTaskProgressResponse"];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalCallbackCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTaskCallbackResponse"];
                };
            };
        };
    };
    callback_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FulfillmentCallbackCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultFulfillmentCallbackResponse"];
                };
            };
        };
    };
}
