/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/common/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 门户档案 */
        get: operations["profile"];
        /** 修改昵称 */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改密码 */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/track/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 客户端批量上报
         * @description 匿名可访问；部分接受；错误 track.batch.overflow / track.batch.rate-limited / common.param-invalid
         */
        post: operations["batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/{taskId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 领取任务 */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/instances/{instanceId}/steps/{stepCode}/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成点击步骤 */
        post: operations["click"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/instances/{instanceId}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户放弃进行中任务 */
        post: operations["abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/signin/{activityId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 今日签到 */
        post: operations["checkin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/signin/{activityId}/catchup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 补签 */
        post: operations["catchup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/prize/records/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 领取奖品 */
        post: operations["claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 门户注册 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 门户登出 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 门户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/ad/materials/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭悬浮素材，消耗当日剩余频控（R30.11） */
        post: operations["dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/activity/{activityId}/participate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 参与活动 */
        post: operations["participate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/{taskId}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** C 端任务详情三分渲染（匿名可访问公开卡，R32.1） */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的任务 */
        get: operations["mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/task/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** C 端任务投放列表（匿名可访问公开卡，R32.1） */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/signin/{activityId}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当月签到日历 */
        get: operations["calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/signin/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** C 端进行中签到活动 */
        get: operations["activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/prize/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的奖品 */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/points/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 积分流水 */
        get: operations["transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/points/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 积分余额 */
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/dict/{typeCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 门户字典项
         * @description 登录态；类型停用返回空列表
         */
        get: operations["entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 门户验证码 */
        get: operations["captcha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/auth/username-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户名可用性 */
        get: operations["usernameAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/ad/positions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拉取广告位素材（匿名可访问，R30.6） */
        get: operations["pull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/activity/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** C 端活动详情（ETag；匿名可访问，R32.1） */
        get: operations["detail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/common/activity/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** C 端进行中活动（匿名可访问，R32.1） */
        get: operations["activities_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PortalNicknameCommand: {
            nickname: string;
        };
        OkResponse: {
            ok?: boolean;
        };
        ResultOkResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["OkResponse"];
            traceId?: string;
        };
        ChangePasswordCommand: {
            oldPassword: string;
            newPassword: string;
        };
        TrackBatchCommand: {
            events?: components["schemas"]["TrackEventCommand"][];
            platform?: string;
            appVersion?: string;
        };
        TrackEventCommand: {
            code?: string;
            props?: unknown;
            clientTime?: string;
        };
        ResultTrackBatchResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TrackBatchResponse"];
            traceId?: string;
        };
        TrackBatchResponse: {
            /** Format: int32 */
            accepted?: number;
            /** Format: int32 */
            dropped?: number;
        };
        CurrentStepView: {
            stepCode?: string;
            name?: string;
            type?: string;
            /** Format: int32 */
            progressCurrent?: number;
            /** Format: int32 */
            progressTarget?: number;
            action?: components["schemas"]["PlatformActionView"];
        };
        PlatformActionView: {
            actionType?: string;
            params?: {
                [key: string]: unknown;
            };
            buttonText?: string;
        };
        ResultTaskStartResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TaskStartResponse"];
            traceId?: string;
        };
        TaskStartResponse: {
            /** Format: int64 */
            instanceId?: number;
            instanceStatus?: string;
            currentStep?: components["schemas"]["CurrentStepView"];
        };
        ResultTaskClickResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TaskClickResponse"];
            traceId?: string;
        };
        RewardFeedbackView: {
            prizeName?: string;
            /** Format: int32 */
            count?: number;
        };
        TaskClickResponse: {
            /** Format: int64 */
            instanceId?: number;
            stepStatus?: string;
            instanceStatus?: string;
            nextStep?: components["schemas"]["CurrentStepView"];
            rewardFeedback?: components["schemas"]["RewardFeedbackView"][];
        };
        InstanceAbandonResponse: {
            instanceStatus?: string;
        };
        ResultInstanceAbandonResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["InstanceAbandonResponse"];
            traceId?: string;
        };
        GrantFeedbackView: {
            /** Format: int32 */
            day?: number;
            /** Format: int64 */
            prizeId?: number;
            status?: string;
            hitIdempotent?: boolean;
        };
        ResultSigninActionResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["SigninActionResponse"];
            traceId?: string;
        };
        SigninActionResponse: {
            alreadySigned?: boolean;
            message?: string;
            /** Format: int64 */
            recordId?: number;
            source?: string;
            /** Format: int32 */
            consecutiveDays?: number;
            rewards?: components["schemas"]["GrantFeedbackView"][];
        };
        CatchupCommand: {
            signDate: string;
        };
        ClaimResponse: {
            status?: string;
            fulfillmentStatus?: string;
        };
        ResultClaimResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["ClaimResponse"];
            traceId?: string;
        };
        PortalRegisterCommand: {
            username: string;
            password: string;
            captchaId: string;
            captchaCode: string;
        };
        PortalAuthResponse: {
            token?: string;
            /** Format: int64 */
            userId?: number;
            nickname?: string;
            mustChangePassword?: boolean;
        };
        ResultPortalAuthResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PortalAuthResponse"];
            traceId?: string;
        };
        PortalLoginCommand: {
            username: string;
            password: string;
            captchaId: string;
            captchaCode: string;
        };
        AdDismissCommand: {
            positionCode: string;
        };
        ParticipateResponse: {
            /** Format: int64 */
            participationId?: number;
            result?: string;
            granted?: boolean;
            /** Format: int64 */
            grantRecordId?: number;
        };
        ResultParticipateResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["ParticipateResponse"];
            traceId?: string;
        };
        InstanceStepView: {
            stepCode?: string;
            name?: string;
            type?: string;
            status?: string;
            /** Format: int32 */
            progressCurrent?: number;
            /** Format: int32 */
            progressTarget?: number;
        };
        ResultTaskDetailResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["TaskDetailResponse"];
            traceId?: string;
        };
        RewardPreviewView: {
            firstName?: string;
            /** Format: int32 */
            totalCount?: number;
        };
        StepPreviewView: {
            /** Format: int32 */
            seq?: number;
            name?: string;
            type?: string;
            /** Format: int32 */
            progressTarget?: number;
        };
        TaskBriefView: {
            name?: string;
            iconUrl?: string;
            description?: string;
            category?: string;
        };
        TaskDetailResponse: {
            status?: string;
            /** Format: int64 */
            instanceId?: number;
            task?: components["schemas"]["TaskBriefView"];
            stepsPreview?: components["schemas"]["StepPreviewView"][];
            rewardPreview?: components["schemas"]["RewardPreviewView"];
            steps?: components["schemas"]["InstanceStepView"][];
            currentStep?: components["schemas"]["CurrentStepView"];
        };
        MineTaskView: {
            /** Format: int64 */
            instanceId?: number;
            /** Format: int64 */
            taskId?: number;
            taskName?: string;
            iconUrl?: string;
            category?: string;
            status?: string;
            currentStepName?: string;
            /** Format: date-time */
            startedAt?: string;
        };
        PageDataMineTaskView: {
            /** Format: int64 */
            total?: number;
            records?: components["schemas"]["MineTaskView"][];
        };
        ResultPageDataMineTaskView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PageDataMineTaskView"];
            traceId?: string;
        };
        PageDataTaskCardView: {
            /** Format: int64 */
            total?: number;
            records?: components["schemas"]["TaskCardView"][];
        };
        ResultPageDataTaskCardView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PageDataTaskCardView"];
            traceId?: string;
        };
        TaskCardView: {
            /** Format: int64 */
            taskId?: number;
            taskCode?: string;
            name?: string;
            category?: string;
            iconUrl?: string;
            badgeText?: string;
            rewardPreview?: components["schemas"]["RewardPreviewView"];
            userStatus?: string;
            /** Format: int32 */
            sortWeight?: number;
        };
        CalendarDayView: {
            /** Format: date */
            date?: string;
            state?: string;
        };
        ResultSigninCalendarResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["SigninCalendarResponse"];
            traceId?: string;
        };
        SigninCalendarResponse: {
            /** Format: int64 */
            activityId?: number;
            activityCode?: string;
            activityName?: string;
            yearMonth?: string;
            /** Format: int32 */
            consecutiveDays?: number;
            /** Format: int32 */
            catchupWindowDays?: number;
            /** Format: int32 */
            catchupDailyLimit?: number;
            /** Format: int32 */
            catchupCostPoints?: number;
            /** Format: int64 */
            pointsBalance?: number;
            /** Format: int32 */
            nextRewardDay?: number;
            /** Format: int64 */
            nextRewardPrizeId?: number;
            nextRewardHint?: string;
            days?: components["schemas"]["CalendarDayView"][];
            tiers?: components["schemas"]["SigninTierView"][];
        };
        SigninTierView: {
            /** Format: int32 */
            day?: number;
            /** Format: int64 */
            prizeId?: number;
        };
        PortalActivityView: {
            /** Format: int64 */
            activityId?: number;
            code?: string;
            name?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
        };
        ResultListPortalActivityView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PortalActivityView"][];
            traceId?: string;
        };
        PageDataPrizeCardView: {
            /** Format: int64 */
            total?: number;
            records?: components["schemas"]["PrizeCardView"][];
        };
        PrizeCardView: {
            /** Format: int64 */
            recordId?: number;
            prizeName?: string;
            prizeImage?: string;
            categoryCode?: string;
            rewardTarget?: string;
            fulfillmentMode?: string;
            status?: string;
            fulfillmentStatus?: string;
            /** Format: date-time */
            expireAt?: string;
            /** Format: date-time */
            obtainedAt?: string;
            /** Format: int64 */
            sourceTaskId?: number;
            sourceTaskName?: string;
            failReason?: string;
            fulfillFailReason?: string;
            /** Format: date-time */
            claimedAt?: string;
            /** Format: int64 */
            activityId?: number;
            activityName?: string;
        };
        ResultPageDataPrizeCardView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PageDataPrizeCardView"];
            traceId?: string;
        };
        PageDataPointsPortalTxView: {
            /** Format: int64 */
            total?: number;
            records?: components["schemas"]["PointsPortalTxView"][];
        };
        PointsPortalTxView: {
            type?: string;
            /** Format: int64 */
            amount?: number;
            /** Format: int64 */
            balanceAfter?: number;
            bizSource?: string;
            /** Format: int64 */
            sourceTaskId?: number;
            remark?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ResultPageDataPointsPortalTxView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PageDataPointsPortalTxView"];
            traceId?: string;
        };
        PointsBalanceResponse: {
            /** Format: int64 */
            balance?: number;
        };
        ResultPointsBalanceResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PointsBalanceResponse"];
            traceId?: string;
        };
        DictPortalEntry: {
            label?: string;
            value?: string;
        };
        ResultListDictPortalEntry: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["DictPortalEntry"][];
            traceId?: string;
        };
        CaptchaResponse: {
            captchaId?: string;
            imageBase64?: string;
        };
        ResultCaptchaResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["CaptchaResponse"];
            traceId?: string;
        };
        ResultUsernameAvailableResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["UsernameAvailableResponse"];
            traceId?: string;
        };
        UsernameAvailableResponse: {
            available?: boolean;
            reason?: string;
        };
        PortalProfileResponse: {
            /** Format: int64 */
            userId?: number;
            username?: string;
            nickname?: string;
            province?: string;
            userLevel?: string;
            userRole?: string;
            tags?: string[];
            /** Format: int64 */
            pointsBalance?: number;
            mustChangePassword?: boolean;
        };
        ResultPortalProfileResponse: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PortalProfileResponse"];
            traceId?: string;
        };
        PortalAdMaterialView: {
            /** Format: int64 */
            materialId?: number;
            trackId?: string;
            title?: string;
            subtitle?: string;
            imageUrl?: string;
            jumpType?: string;
            jumpParams?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            weight?: number;
        };
        PortalAdPositionView: {
            code?: string;
            form?: string;
            materials?: components["schemas"]["PortalAdMaterialView"][];
            /** Format: int32 */
            splashDurationSeconds?: number;
            /** Format: int32 */
            carouselIntervalSeconds?: number;
        };
        ResultPortalAdPositionView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PortalAdPositionView"];
            traceId?: string;
        };
        PortalActivityDetailView: {
            /** Format: int64 */
            id?: number;
            code?: string;
            name?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            richText?: string;
            contentHash?: string;
            /** Format: int32 */
            version?: number;
            submodules?: components["schemas"]["SubmoduleView"][];
        };
        ResultPortalActivityDetailView: {
            code?: unknown;
            message?: string;
            data?: components["schemas"]["PortalActivityDetailView"];
            traceId?: string;
        };
        SubmoduleView: {
            type?: string;
            /** Format: int64 */
            refId?: number;
            /** Format: int32 */
            sort?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPortalProfileResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalNicknameCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOkResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOkResponse"];
                };
            };
        };
    };
    batch: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackBatchCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTrackBatchResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
                "X-Client-Platform"?: string;
            };
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTaskStartResponse"];
                };
            };
        };
    };
    click: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
                "X-Client-Platform"?: string;
            };
            path: {
                instanceId: number;
                stepCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTaskClickResponse"];
                };
            };
        };
    };
    abandon: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path: {
                instanceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultInstanceAbandonResponse"];
                };
            };
        };
    };
    checkin: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSigninActionResponse"];
                };
            };
        };
    };
    catchup: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatchupCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSigninActionResponse"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultClaimResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalRegisterCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPortalAuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOkResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalLoginCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPortalAuthResponse"];
                };
            };
        };
    };
    dismiss: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdDismissCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultOkResponse"];
                };
            };
        };
    };
    participate: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
            };
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultParticipateResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Platform"?: string;
            };
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultTaskDetailResponse"];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: {
                status?: string;
                category?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageDataMineTaskView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                category?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageDataTaskCardView"];
                };
            };
        };
    };
    calendar: {
        parameters: {
            query?: {
                yearMonth?: string;
            };
            header?: never;
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultSigninCalendarResponse"];
                };
            };
        };
    };
    activities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListPortalActivityView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                tab?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageDataPrizeCardView"];
                };
            };
        };
    };
    transactions: {
        parameters: {
            query?: {
                type?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPageDataPointsPortalTxView"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPointsBalanceResponse"];
                };
            };
        };
    };
    entries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                typeCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListDictPortalEntry"];
                };
            };
        };
    };
    captcha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultCaptchaResponse"];
                };
            };
        };
    };
    usernameAvailable: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultUsernameAvailableResponse"];
                };
            };
        };
    };
    pull: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Id"?: string;
                "X-Client-Platform"?: string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPortalAdPositionView"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                activityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultPortalActivityDetailView"];
                };
            };
        };
    };
    activities_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultListPortalActivityView"];
                };
            };
        };
    };
}
