spring:
  application:
    name: admin-app
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${MKT_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/mkt_platform?characterEncoding=utf8&connectionTimeZone=UTC}
    username: ${MKT_DATASOURCE_USERNAME:mkt}
    password: ${MKT_DATASOURCE_PASSWORD:}

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    enabled: false
