/** Backend closed enums / seeds. Do not invent codes. */
export const STATUS = {
  ENABLED: "ENABLED",
  DISABLED: "DISABLED",
} as const;

export const ACCOUNT_TYPE = {
  ADMIN: "admin",
  PORTAL: "portal",
} as const;

export const SUPER_ADMIN_ROLE = "super-admin";
export const SUPER_ADMIN_USERNAME = "admin";

export const PERMS = {
  USER_QUERY: "identity:admin-user:query",
  USER_CREATE: "identity:admin-user:create",
  USER_UPDATE: "identity:admin-user:update",
  USER_DISABLE: "identity:admin-user:disable",
  USER_RESET: "identity:admin-user:reset-password",
  USER_DELETE: "identity:admin-user:delete",
  ROLE_QUERY: "identity:role:query",
  ROLE_CREATE: "identity:role:create",
  ROLE_UPDATE: "identity:role:update",
  ROLE_DELETE: "identity:role:delete",
  ROLE_ASSIGN: "identity:role:assign-permission",
  PERMISSION_QUERY: "identity:permission:query",
  PORTAL_QUERY: "identity:portal-user:query",
  PORTAL_PROFILE: "identity:portal-user:update-profile",
  PORTAL_DISABLE: "identity:portal-user:disable",
  PORTAL_RESET: "identity:portal-user:reset-password",
  PORTAL_DELETE: "identity:portal-user:delete",
  SESSION_QUERY: "identity:session:query",
  SESSION_KICK: "identity:session:kick",
  APP_QUERY: "identity:internal-app:query",
  APP_ADD: "identity:internal-app:add",
  APP_EDIT: "identity:internal-app:edit",
  DICT_TYPE_QUERY: "system:dict-type:query",
  DICT_TYPE_CREATE: "system:dict-type:create",
  DICT_TYPE_UPDATE: "system:dict-type:update",
  DICT_TYPE_DELETE: "system:dict-type:delete",
  DICT_ENTRY_CREATE: "system:dict-entry:create",
  CONFIG_QUERY: "system:config:query",
  CONFIG_CREATE: "system:config:create",
  CONFIG_UPDATE: "system:config:update",
  CACHE_STATS: "system:cache:stats",
  CACHE_EVICT: "system:cache:evict",
  AUDIT_QUERY: "system:audit:query",
  TASK_DEF_QUERY: "task:definition:query",
  TASK_DEF_CREATE: "task:definition:create",
  TASK_DEF_UPDATE: "task:definition:update",
  TASK_DEF_COPY: "task:definition:copy",
  TASK_DEF_DELETE: "task:definition:delete",
  TASK_DEF_PUBLISH: "task:definition:publish",
  TASK_DEF_SCHEDULE: "task:definition:schedule",
  TASK_DEF_OFFLINE: "task:definition:offline",
  TASK_EXPR_VALIDATE: "task:expression:validate",
  TASK_MUTEX_QUERY: "task:mutex-group:query",
  TASK_MUTEX_CREATE: "task:mutex-group:create",
  TASK_MUTEX_UPDATE: "task:mutex-group:update",
  TASK_MUTEX_DELETE: "task:mutex-group:delete",
  TASK_CROWD_QUERY: "task:crowd:query",
  TASK_CROWD_CREATE: "task:crowd:create",
  TASK_CROWD_UPDATE: "task:crowd:update",
  TASK_CROWD_DELETE: "task:crowd:delete",
  TASK_INSTANCE_QUERY: "task:instance:query",
  TASK_INSTANCE_ABANDON: "task:instance:abandon",
  REWARD_CAT_QUERY: "reward:category:query",
  REWARD_CAT_CREATE: "reward:category:create",
  REWARD_CAT_UPDATE: "reward:category:update",
  REWARD_CAT_DELETE: "reward:category:delete",
  REWARD_CAT_DISABLE: "reward:category:disable",
  REWARD_CAT_ENABLE: "reward:category:enable",
  REWARD_PRIZE_QUERY: "reward:prize:query",
  REWARD_PRIZE_CREATE: "reward:prize:create",
  REWARD_PRIZE_UPDATE: "reward:prize:update",
  REWARD_PRIZE_DELETE: "reward:prize:delete",
  REWARD_PRIZE_DISABLE: "reward:prize:disable",
  REWARD_PRIZE_ENABLE: "reward:prize:enable",
  REWARD_PRIZE_STOCK: "reward:prize:stock-replenish",
  REWARD_RECORD_QUERY: "reward:record:query",
  REWARD_RECORD_RETRY: "reward:record:retry",
  REWARD_RECORD_FULFILL: "reward:record:fulfill",
  REWARD_RECORD_MANUAL: "reward:record:manual-grant",
  REWARD_RECON_QUERY: "reward:recon:query",
  REWARD_RECON_IMPORT: "reward:recon:import",
  REWARD_RECON_MATCH: "reward:recon:match",
  REWARD_RECON_ACTION: "reward:recon:action",
  POINTS_ACCOUNT_QUERY: "points:account:query",
  POINTS_ACCOUNT_ADJUST: "points:account:adjust",
  POINTS_TX_QUERY: "points:transaction:query",
  RISK_BLACK_QUERY: "risk:blacklist:query",
  RISK_BLACK_ADD: "risk:blacklist:add",
  RISK_BLACK_REMOVE: "risk:blacklist:remove",
  RISK_BLACK_IMPORT: "risk:blacklist:import",
  RISK_WHITE_QUERY: "risk:whitelist:query",
  RISK_WHITE_ADD: "risk:whitelist:add",
  RISK_WHITE_REMOVE: "risk:whitelist:remove",
  RISK_RULE_QUERY: "risk:rule:query",
  RISK_RULE_CONFIG: "risk:rule:config",
  RISK_CASE_QUERY: "risk:case:query",
  RISK_CASE_HANDLE: "risk:case:handle",
  TRACK_META_QUERY: "track:metadata:query",
  TRACK_META_CREATE: "track:metadata:create",
  TRACK_META_UPDATE: "track:metadata:update",
  TRACK_META_DELETE: "track:metadata:delete",
  TRACK_EVENT_QUERY: "track:event:query",
} as const;

export const CONFIG_VALUE_TYPES = ["STRING", "NUMBER", "BOOL", "JSON"] as const;
