/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdCarousel: typeof import('./src/components/AdCarousel.vue')['default']
    AdFloat: typeof import('./src/components/AdFloat.vue')['default']
    AdPopup: typeof import('./src/components/AdPopup.vue')['default']
    AdSplash: typeof import('./src/components/AdSplash.vue')['default']
    CaptchaField: typeof import('./src/components/CaptchaField.vue')['default']
    FallbackImage: typeof import('./src/components/FallbackImage.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginOverlay: typeof import('./src/components/LoginOverlay.vue')['default']
    PrizeCard: typeof import('./src/components/PrizeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SigninMonthGrid: typeof import('./src/components/SigninMonthGrid.vue')['default']
    SigninWeekRow: typeof import('./src/components/SigninWeekRow.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskCompletePanel: typeof import('./src/components/TaskCompletePanel.vue')['default']
    TaskCompleteSheet: typeof import('./src/components/TaskCompleteSheet.vue')['default']
    TaskTimeline: typeof import('./src/components/TaskTimeline.vue')['default']
  }
}
