import {
  AccountBookOutlined,
  AlertOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BlockOutlined,
  BookOutlined,
  BugOutlined,
  CalendarOutlined,
  CloudServerOutlined,
  ClusterOutlined,
  ControlOutlined,
  DatabaseOutlined,
  ExperimentOutlined,
  FileImageOutlined,
  FileOutlined,
  FileProtectOutlined,
  GiftOutlined,
  LayoutOutlined,
  MobileOutlined,
  PlayCircleOutlined,
  ProfileOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  StopOutlined,
  TagsOutlined,
  TeamOutlined,
  TransactionOutlined,
  UnorderedListOutlined,
  UserOutlined,
  UserSwitchOutlined,
  WalletOutlined,
} from "@ant-design/icons-vue";
import type { Component } from "vue";

const ROUTE_ICONS: [string, Component][] = [
  ["/system/users", UserOutlined],
  ["/system/roles", SafetyCertificateOutlined],
  ["/system/sessions", UserSwitchOutlined],
  ["/system/portal-users", MobileOutlined],
  ["/system/internal-apps", ApiOutlined],
  ["/system/dicts", BookOutlined],
  ["/system/configs", ControlOutlined],
  ["/system/cache", CloudServerOutlined],
  ["/system/audits", AuditOutlined],
  ["/task/definitions", UnorderedListOutlined],
  ["/task/mutex-groups", BlockOutlined],
  ["/task/crowds", ClusterOutlined],
  ["/task/instances", PlayCircleOutlined],
  ["/reward/categories", AppstoreOutlined],
  ["/reward/prizes", GiftOutlined],
  ["/reward/records", ProfileOutlined],
  ["/reward/recon", AccountBookOutlined],
  ["/points/accounts", WalletOutlined],
  ["/points/transactions", TransactionOutlined],
  ["/risk/list-items", StopOutlined],
  ["/risk/rules", FileProtectOutlined],
  ["/risk/cases", AlertOutlined],
  ["/track/metadata", DatabaseOutlined],
  ["/track/events", BugOutlined],
  ["/signin/activities", CalendarOutlined],
  ["/signin/records", ScheduleOutlined],
  ["/activity/activities", TagsOutlined],
  ["/activity/participations", TeamOutlined],
  ["/ad/positions", LayoutOutlined],
  ["/ad/materials", FileImageOutlined],
  ["/metrics", BarChartOutlined],
  ["/simulate", ExperimentOutlined],
];

const ROUTE_ICONS_BY_LENGTH = [...ROUTE_ICONS].sort((left, right) => right[0].length - left[0].length);

export function iconForMenuRoute(route: string | undefined | null): Component {
  const path = route ?? "";
  const match = ROUTE_ICONS_BY_LENGTH.find(([prefix]) => path === prefix || path.startsWith(`${prefix}/`));
  return match?.[1] ?? FileOutlined;
}
