package com.mkt.identity.domain;

import java.util.List;
import java.util.Set;

/**
 * Closed P0 operation codes from requirements appendix B / design §4.2–§4.7.
 * Super-admin owns this set even before OPERATION nodes exist in the tree (R2.5).
 */
public final class AdminPermissionCatalog {

    public static final List<String> P0 = List.of(
            "identity:admin-user:create",
            "identity:admin-user:update",
            "identity:admin-user:disable",
            "identity:admin-user:reset-password",
            "identity:admin-user:delete",
            "identity:admin-user:query",
            "identity:role:create",
            "identity:role:update",
            "identity:role:delete",
            "identity:role:assign-permission",
            "identity:role:query",
            "identity:permission:create",
            "identity:permission:update",
            "identity:permission:delete",
            "identity:permission:query",
            "identity:portal-user:query",
            "identity:portal-user:update-profile",
            "identity:portal-user:disable",
            "identity:portal-user:reset-password",
            "identity:portal-user:delete",
            "identity:session:query",
            "identity:session:kick",
            "identity:internal-app:query",
            "identity:internal-app:add",
            "identity:internal-app:edit",
            "system:dict-type:query",
            "system:dict-type:create",
            "system:dict-type:update",
            "system:dict-type:delete",
            "system:dict-entry:create",
            "system:dict-entry:update",
            "system:dict-entry:delete",
            "system:config:query",
            "system:config:create",
            "system:config:update",
            "system:cache:stats",
            "system:cache:evict",
            "system:audit:query",
            "task:definition:create",
            "task:definition:update",
            "task:definition:publish",
            "task:definition:offline",
            "task:definition:schedule",
            "task:definition:copy",
            "task:definition:delete",
            "task:definition:query",
            "task:expression:validate",
            "task:mutex-group:query",
            "task:mutex-group:create",
            "task:mutex-group:update",
            "task:mutex-group:delete",
            "task:crowd:query",
            "task:crowd:create",
            "task:crowd:update",
            "task:crowd:delete",
            "task:instance:query",
            "task:instance:abandon",
            "reward:prize:create",
            "reward:prize:update",
            "reward:prize:disable",
            "reward:prize:enable",
            "reward:prize:delete",
            "reward:prize:query",
            "reward:prize:stock-replenish",
            "reward:prize-group:query",
            "reward:prize-group:create",
            "reward:prize-group:update",
            "reward:prize-group:delete",
            "reward:category:query",
            "reward:category:create",
            "reward:category:update",
            "reward:category:disable",
            "reward:record:query",
            "reward:record:retry",
            "reward:record:manual-grant",
            "reward:record:fulfill",
            "reward:recon:query",
            "reward:recon:import",
            "reward:recon:match",
            "reward:recon:action",
            "points:account:query",
            "points:account:adjust",
            "points:transaction:query",
            "risk:blacklist:add",
            "risk:blacklist:import",
            "risk:blacklist:remove",
            "risk:blacklist:query",
            "risk:whitelist:add",
            "risk:whitelist:remove",
            "risk:whitelist:query",
            "risk:rule:config",
            "risk:rule:query",
            "risk:case:handle",
            "risk:case:query",
            "track:metadata:query",
            "track:metadata:create",
            "track:metadata:update",
            "track:metadata:delete",
            "track:event:query");

    public static final Set<String> P0_SET = Set.copyOf(P0);

    private AdminPermissionCatalog() {}
}
